### ISSUE TITLE
I have run the code "covid19_pneumonia_detection_cnn_model.py", What to do next？

### ISSUE THREAD

**Issue by gen2020code** [montusharma550/covid19_detection#1]
I have run the code "covid19_pneumonia_detection_cnn_model.py", What to do next？

**Comment by aniruddh-1** [comment]
Hello

Download and place the pickle datasets in the same folder where your code
is. You can Download the pickle datasets from this link
<https://github.com/aniruddh-1/COVID19_Pneumonia_detection/tree/master/ct_scan_pickle_dataset>
.
You can also make your own pickle datasets and import them in the code.

Thanks
